### ISSUE TITLE
Please add jar into maven repository, oss snapshots or vaadin

### ISSUE THREAD

**Issue by zhuravskiy** [Artur-/portal-push#1]
> The POM for org.vaadin.artur:portal-push:jar:1.0-SNAPSHOT is missing, no dependency information available

Thanks!

**Comment by Artur-** [comment]
It will be, until then you can just run `mvn install` on this project

**Comment by zhuravskiy** [comment]
:) i know it, i installed it in a local maven repository, but all member of my team must do same, more easily when artifact published into some internet repository already. Ok as temporary solution we install it in our private nexus repository.

**Comment by Artur-** [comment]
https://vaadin.com/directory#!addon/portal-push-add-on
