### ISSUE TITLE
Session Expired - vaadin 7.6.8

### ISSUE THREAD

**Issue by dcabrera22** [Artur-/portal-push#2]
Hello. I'm using vaadin 7.6.8 in Liferay CE 6.2-ga5
I have problem with the portal-push-demo.war. "Session Expired"

![vaadin portal push demo - session expired 1](https://cloud.githubusercontent.com/assets/5774497/17102425/e70b2b44-524f-11e6-975d-3776c9fef755.jpg)
![vaadin portal push demo - session expired 2](https://cloud.githubusercontent.com/assets/5774497/17102426/e724f7cc-524f-11e6-9f90-203cb6e2da2b.jpg)

Any solution?
Thanks
Diego

**Comment by Artur-** [comment]
When does this happen?

**Comment by dcabrera22** [comment]
Hello Artur. thanks for your response
Like I said before, download your demo. I compiled it with vaadin 7.6.8 and put the war in liferay CE 6.2
The new Portlet appear to add in liferay.
I added in a page and instantaneously appears the message "Session Expired" (like yo can see in the first image attached)
The second image was when I did a refresh of the Page (F5)

**Comment by Artur-** [comment]
Interesting, I just tried exactly the same thing and could not see any session expired message. What do the logs tell you, Liferay logs and/or browser console logs.

**Comment by dcabrera22** [comment]
Firefox Console Log

![vaadin demo push - console log 1](https://cloud.githubusercontent.com/assets/5774497/17188915/962c06ea-5415-11e6-81dc-a2e7797bef4b.jpg)
![vaadin demo push - console log 2](https://cloud.githubusercontent.com/assets/5774497/17188918/97de3fee-5415-11e6-8f7c-f71a3b81e573.jpg)
![vaadin demo push - console log 3](https://cloud.githubusercontent.com/assets/5774497/17188920/99947678-5415-11e6-9f84-097118558a9a.jpg)

**Comment by Artur-** [comment]
Looks like the server does not find the session when the push connection is established. Anything in the Liferay logs?

**Comment by dcabrera22** [comment]
Artur, I just download liferay again (without our changes) and works perfectly :)
The problem, is the property "session.enable.phishing.protection=false" that we had in the portal-ext-properties.
We need this because we use CAS to login to liferay (and works only with this property in false).
Difficult conflict.

We have to ask to CAS and Liferay people, another solution without this property in false.

Thanks a lot for your time.
Regards
Diego from Uruguay

**Comment by dcabrera22** [comment]
Sorry Artur, but is not that.
Is somethings cached in the browser.
If I clean the browser cache and cookies, works again.

Any idea?

**Comment by Artur-** [comment]
Any way to reproduce the problem?

In the browser there should be a JSESSIONID cookie for "/" and none for "/portal-push-demo" or whatever your _war_ file name is. 

If you look at the network inspector in the browser, you should see that the server sets the JSESSIONID in the response for the request containing "p_p_resource_id=v-browserDetails" in the URL. The same JSESSIONID should then be sent to the server in the "ws://localhost:8080/portal-push-demo-1.0-SNAPSHOT/PUSH" request

**Comment by dcabrera22** [comment]
Sorry Artur, I forgot to tell you how reproduce.
First, appear to works fine in a liferay page in Firefox.
Second, restart liferay (shutdown and start again)
Finally, refresh Liferay page in the navigator and I see the "Session Expired"

If I clean all the cache and cookie, works again

**Comment by Artur-** [comment]
Finally found some time to look into this. It seems Vaadin was prevented from creating a servlet session (as opposed to a portlet session) but Atmosphere was not.
